### ISSUE TITLE
Feature request: Support Permission Boundaries

### ISSUE THREAD

**Issue by Seth-Karlo** [terraform-redhat/terraform-aws-rosa-sts#12]
We have customers who have restrictions in place that the operator and account roles cannot be created without having a permissions boundary. This is supported in the aws_iam_role but not available via the module yet.

**Comment by Scorpiion** [comment]
I work together with @Seth-Karlo in the Red Hat EMEA Black Belt team. I just wanted to add that this is supported in the rosa cli:

```
$ rosa create operator-roles --help

....

Examples:
  # Create operator roles with a specific permissions boundary
  rosa create operator-roles -c mycluster --permissions-boundary arn:aws:iam::123456789012:policy/perm-boundary

Flags:
...
      --permissions-boundary string   The ARN of the policy that is used to set the permissions boundary for the operator roles.
...
```

We would like to use this same feature in terraform.

**Comment by bardielle** [comment]
I opened a PR for that :
https://github.com/terraform-redhat/terraform-aws-rosa-sts/pull/13

**Comment by Seth-Karlo** [comment]
Thanks very much!
