### ISSUE TITLE
provide option to pass tags to module

### ISSUE THREAD

**Issue by vamsinm** [terraform-redhat/terraform-aws-rosa-sts#8]
please provide option to pass tags to module so they can be populated on AWS Resouces created to meet organizational specific tagging requirements.

**Comment by vamsinm** [comment]
https://github.com/terraform-redhat/terraform-aws-rosa-sts/pull/10

**Comment by arendej** [comment]
There are two paths at this time for AWS tags within our Terraform content for ROSA...
1. any tags passed via the native AWS Terraform resources would be sent to those resources 
2a. any tags passed to ROSA cluster at creation time would be send to those resources
2b. any tags passed day2(beyond cluster install) are not yet reconciled by ROSA/OpenShift, and this is pending a RFE in OpenShift upstream.

**Comment by vamsinm** [comment]
@arendej Can you please elaborate a bit more on comments posted when closing the issue: 

1. any tags passed via the native AWS Terraform resources would be sent to those resources : 
     `how are these tags passed to these resources when i am using this terraform module?`

2a. any tags passed via the native AWS Terraform resources would be sent to those resources:
    `if i create account roles or operator roles through this module and when i create a ROSA cluster and pass tags at the creation time, would that automatically update tags on account role and operator roles created through this module? in that case since account roles are created once, what happens when i build multiple clusters with different  tags?`

.2b. any tags passed day2(beyond cluster install) are not yet reconciled by ROSA/OpenShift, and this is pending a RFE in OpenShift upstream. Once we get that feature, we inherit it and it will be worked into our ROSA Terraform resources.
      ` same question as 2a. `
